import { Inter } from 'next/font/google';
import '@styles/tailwind.css';
import Header from '@components/Header';
import Nav from '@common/Nav';
import { ProviderAuth } from '@hooks/useAuth';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ProviderAuth>
          <div className="min-h-full">
            <Header />
            <Nav />
            <main>
              <div className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">{children}</div>
            </main>
          </div>
        </ProviderAuth>
      </body>
    </html>
  );
}
